### ISSUE TITLE
Question: How does one share resources between projects

### ISSUE THREAD

**Issue by dsifford** [manifoldco/manifold-cli#234]
Hello there,

Sorry if this is not the proper venue for this. I've got hopefully a simple question that might be useful for others as well.

Consider a situation where I have 2 distinct projects, both of which use service `SERVICE_A`, but otherwise using uniquely distinct services.

```yml
projects:
    project_1:
        - SERVICE_X
        - SERVICE_A

    project_2:
        - SERVICE_Y
        - SERVICE_A

other_resources:
    - SERVICE_A
```

Is it at all possible to pull a single resource (`SERVICE_A`) from the global pool to use in both projects, without having to add the keys manually to both projects? Is there perhaps some setting that can be added to `.manifold.yml` that can make this happen?

The salient use-case here for me is sharing keys between development and production for a subset of services used, but using distinct production and development keys for the rest.

Thanks for clarifying.
